<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<title>System Debugger</title>
<link rel="stylesheet" type="text/css" href="style.css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="iecss.css" />
<![endif]-->
<script type="text/javascript" src="js/boxOver.js"></script>
</head>
<body>
<div id="main_container">

  <div id="header"> </div>
<!-- end of oferte_content-->

  <div id="main_content">
    <div id="menu_tab">
      <div class="left_menu_corner"></div>
      <ul class="menu">
        <li><a href="index.php" class="nav1">HOME</a></li>
        <li class="divider"></li>
        <li><a href="reviews.php" class="nav3">REVIEWS</a></li>
        <li class="divider"></li>
        <li><a href="register.php" class="nav4">NEW REGISTRATION</a></li>
        <li class="divider"></li>
        <li><a href="#" class="nav5">SHOPPING</a></li>
        <li class="divider"></li>
        <li><a href="contact.php" class="nav6">CONTACT US</a></li>
        <li class="divider"></li>
        <li><a href="#" class="nav4">SIGN UP</a></li>
      </ul>
      <div class="right_menu_corner"></div>
    </div>
    <!-- end of menu tab -->
    
    <div class="left_content">
      <div class="title_box">CATEGORIES</div>
<ul class="left_menu">
<?php
include("categories.php");
?>
      </ul>
      <div class="banner_adds"> <a href="#"><img src="images/bann2.jpg" alt="" title="" border="0" /></a> </div>
      <div class="banner_adds"> <a href="#"><img src="images/bann1.jpg" alt="" title="" border="0" /></a> </div>
    </div>
    <!-- end of left content -->
    
    <div class="center_content">
      <div class="center_title_bar">HP
      <div class="hp_m" align="left" margin_left="0px">
      <form action="" method="post" >
      <table border="1px" align="center" style="background:#009541">
      <tr>
      <td>
         <div class="category_box">
         <div class="product_title">HP 18-1205IN All-in-One</div>
         <div class="product_img"><img src="images/hp/HP 18-1205IN All-in-One.jpg" height="90" width="100" /></div>
         <div class="prod_price">APU Dual Core/ 4GB/ 500GB/ Win8 &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=1">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP 250-E8D87PA Laptop</div>
         <div class="product_img"><img src="images/hp/HP 250-E8D87PA Laptop.jpg"  height="90" width="100" /></div>
         <div class="prod_price">3rd Gen Ci3/ 4GB/ 500GB/ DOS &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=2">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP 500 GB Hard Disk</div>
         <div class="product_img"><img src="images/hp/HP 500 GB hdd.jpg"  height="90" width="100" /></div>
         <div class="prod_price">Connectivity: USB 3.0<br /> &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=3">Read More</a></div>
         </div>
      </td>
      </tr>
      <tr>
      <td>
         <div class="category_box">
         <div class="product_title">HP Envy 15 Touchsmart Laptop</div>
         <div class="product_img"><img src="images/hp/HP Envy 15 15 Touchsmart Laptop.jpg" height="90" width="100" /></div>
         <div class="prod_price">Core i7/8 GB RAM/500 GB HDD/Windows 8 &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=4">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP LCD Monitor</div>
         <div class="product_img"><img src="images/hp/HP LCD Monitor.jpg"  height="90" width="100" /></div>
         <div class="prod_price">Backlit LCD/HD Display/IPS Panel &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=5">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP Pavilion DV6-6155TX Laptop</div>
         <div class="product_img"><img src="images/hp/HP Pavilion DV6-6155TX Laptop.jpg"  height="90" width="100" /></div>
         <div class="prod_price">2nd Gen Ci5/ 4GB/ 750GB/ Win7 HB &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=6">Read More</a></div>
         </div>
      </td>
      </tr>
      <tr>
      <td>
         <div class="category_box">
         <div class="product_title">HP Pavilion 15-n208TX Laptop</div>
         <div class="product_img"><img src="images/hp/HP Pavilion 15-n208TX Laptop.jpg" height="90" width="100" /></div>
         <div class="prod_price">4th Gen Ci5/ 4GB/ 1TB/ Win8.1&nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=7">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP 15-D005TU Laptop</div>
         <div class="product_img"><img src="images/hp/HP 15-D005TU Laptop.jpg"height="90" width="100" /></div>
         <div class="prod_price">Gen Ci3/ 4GB/ 500GB/ Win8.1 &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=8">Read More</a></div>
         </div>
      </td>
      <td>
         <div class="category_box">
         <div class="product_title">HP Compaq 15-a002TU Laptop</div>
         <div class="product_img"><img src="images/hp/HP Compaq 15-a002TU Laptop.jpg" height="90" width="100" /></div>
         <div class="prod_price">Gen Ci3/ 4GB/ 500GB/ DOS &nbsp;&nbsp;&nbsp;<a href="hp_buy.php?val=9">Read More</a></div>
         </div>
      </td>
      </tr>
      </table>
      </form>
      </div>
      
      </div>
    </div>
    <!-- end of center content -->
    
    <div class="right_content">
<div class="banner_adds"> <a href="#"><img src="images/shopping-cart.jpg" width="190" height="130" style="border-radius:7px 7px 7px 7px" /></a> </div>      <div class="title_box">MANUFACTURERS</div>
<?php
include("manufacture.php");
?>      
<div class="title_box">COMPANIES</div>
      <div class="border_box">
        <div class="product_img">
<?php
include("marquee.php");
?>
        </div>
      </div>
    </div>
    <!-- end of right content --> 
    
  </div>
  <!-- end of main content -->
<?php
  include("footer.php");
?>

<!-- end of main_container -->
</body>
</html>